fuse: Fix installed-vs-shipped for nativesdk
There are two problems:
* The /dev is installed to '${D}/dev', not '${D}${base_prefix}'
* The /etc is installed ${D}, but should be ${D}${sysconfdir}

It works for target is because target's base_prefix is NULL, but it isn't work
for native or nativesdk.

Fixed:
$ bitbake nativesdk-fuse
ERROR: nativesdk-fuse-2.9.9-r0 do_package: QA Issue: nativesdk-fuse: Files/directories were installed but not shipped in any package:
  /dev
  /etc
  /etc/init.d
  /etc/udev
  /etc/init.d/fuse
  /etc/udev/rules.d
  /etc/udev/rules.d/99-fuse.rules

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>