samba: remove ${localstatedir}/log
Fixed do_package error:
WARNING: samba-4.4.2-r0 do_package: FILES contains file '/var/log/samba' which resides under a directory symlink. Please fix the recipe and use the real path for the file.
ERROR: samba-4.4.2-r0 do_package: File './var/log/samba' cannot be packaged into 'samba-base' because its parent directory structure does not exist. One of its parent directories is a symlink whose target directory is not included in the package.
ERROR: samba-4.4.2-r0 do_package: Function failed: populate_packages

It has a file ${sysconfdir}/tmpfiles.d/samba.conf which will create
/var/log/samba when systemd, and volatiles.03_samba when sysvinit.

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
Signed-off-by: Joe MacDonald <joe_macdonald@mentor.com>
(cherry picked from commit 74d994ed27e53370101a3a44f25cd07327d774ad)
Signed-off-by: Andreas Oberritter <obi@opendreambox.org>