libagg: add recipe for v2.4.0
Anti-Grain Geometry (AGG) is an Open Source, free of charge graphic library,
written in industrially standard C++. The terms and conditions of use AGG are
described on The License page. AGG doesn't depend on any graphic API or
technology. Basically, you can think of AGG as of a rendering engine that
produces pixel images in memory from some vectorial data. But of course, AGG
can do much more than that.

libagg is a dependency of python-matplotlib. Matplotlib bundles the source,
but this is generally considered poor practice in the context of embedded.

* Add patch to fix/suppress:
configure.ac:11: error: automatic de-ANSI-fication support has been removed
<build>/tmp/work/i586-poky-linux/libagg/2.4.0-r0/recipe-sysroot-native/usr/share/aclocal-1.15/obsolete.m4:26: AM_C_PROTOTYPES is expanded from...
configure.ac:11: the top level
autom4te: m4 failed with exit status: 1
aclocal: error: echo failed with exit status: 1
autoreconf: aclocal failed with exit status: 1
ERROR: autoreconf execution failed.

Signed-off-by: Tim Orling <timothy.t.orling@linux.intel.com>