flatcc: respect baselib
* avoid installed-vs-shipped with multilib when baselib is lib32 or lib64 instead of just lib

ERROR: QA Issue: lib32-flatcc: Files/directories were installed but not shipped in any package:
  /usr/lib
  /usr/lib/libflatcc.a
  /usr/lib/libflatccrt.a
Please set FILES such that these items are packaged. Alternatively if they are unneeded, avoid installing them or delete them within do_install.
lib32-flatcc: 3 installed and not shipped files. [installed-vs-shipped]

Signed-off-by: Martin Jansa <martin.jansa@gmail.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>