SIGGEN_EXCLUDE_SAFE_RECIPE_DEPS add lsb and util-linux for phoronix-test-suite
* phoronix-test-suite is allarch, but util-linux and lsb aren't
   === Comparing signatures for task do_package_write_ipk.sigdata between qemux86 and qemux86copy ===
  ERROR: phoronix-test-suite different signature for task do_package_write_ipk.sigdata between qemux86 and qemux86copy
  Hash for dependent task lsb/lsb_5.0.bb.do_packagedata changed from 7baca400e354b600fe967ea615032052 to 67888a6c7511339a873b547745287ef2

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>