rarpd, sblim-sfcb, openct: inherit systemd unconditionally
* the inherit was controlled by VIRTUAL-RUNTIME_init_manager and the installation
  of .service files by DISTRO_FEATURES and systemd was in DISTRO_FEATURES but not
  in VIRTUAL-RUNTIME_init_manager it was causing QA issues about unpackaged
  .service files

ERROR: rarpd-ss981107-r0 do_package: QA Issue: rarpd: Files/directories
were installed but not shipped in any package:
  /lib
  /lib/systemd
  /lib/systemd/system
  /lib/systemd/system/rarpd.service

ERROR: sblim-sfcb-1.4.9-r0 do_package: QA Issue: sblim-sfcb:
Files/directories were installed but not shipped in any package:
  /lib
  /lib/systemd
  /lib/systemd/system
  /lib/systemd/system/sblim-sfcb.service

ERROR: sblim-sfcb-1.4.9-r0 do_package: QA Issue: sblim-sfcb:
Files/directories were installed but not shipped in any package:
  /lib
  /lib/systemd
  /lib/systemd/system
  /lib/systemd/system/sblim-sfcb.service

* systemd.bbclass will take care of removing /lib/systemd when systemd
  isn't in DISTRO_FEATURES, so we can remove both conditions

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>