WIP: pipewire: accept webrtc-audio-processing-1
This isn't complete still fails with:
http://errors.yoctoproject.org/Errors/Details/698127/
and after fixing this include (by dropping webrtc prefix), the other 2 includes don't exist anymore as well and fails with:
http://errors.yoctoproject.org/Errors/Details/698129/

FAILED: spa/plugins/aec/libspa-aec-webrtc.so.p/aec-webrtc.cpp.o
x86_64-oe-linux-g++ -m64 -march=core2 -mtune=core2 -msse3 -mfpmath=sse -fstack-protector-strong -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security --sysroot=TOPDIR/tmp-glibc/work/core2-64-oe-linux/pipewire/0.3.67-r0/recipe-sysroot -Ispa/plugins/aec/libspa-aec-webrtc.so.p -Ispa/plugins/aec -I../git/spa/plugins/aec -I. -I../git -Ispa/include -I../git/spa/include -ITOPDIR/tmp-glibc/work/core2-64-oe-linux/pipewire/0.3.67-r0/recipe-sysroot/usr/include/webrtc-audio-processing-1 -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Wpedantic -std=c++17 -fvisibility=hidden -fno-strict-aliasing -Werror=suggest-attribute=format -Wsign-compare -Wpointer-arith -Wformat -Wformat-security -Wimplicit-fallthrough -Wmissing-braces -Wtype-limits -Wvariadic-macros -Wmaybe-uninitialized -Wno-missing-field-initializers -Wno-unused-parameter -Wno-pedantic -Wdeprecated-declarations -Wunused-result -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=TOPDIR/tmp-glibc/work/core2-64-oe-linux/pipewire/0.3.67-r0/git=/usr/src/debug/pipewire/0.3.67-r0 -fdebug-prefix-map=TOPDIR/tmp-glibc/work/core2-64-oe-linux/pipewire/0.3.67-r0/git=/usr/src/debug/pipewire/0.3.67-r0 -fmacro-prefix-map=TOPDIR/tmp-glibc/work/core2-64-oe-linux/pipewire/0.3.67-r0/build=/usr/src/debug/pipewire/0.3.67-r0 -fdebug-prefix-map=TOPDIR/tmp-glibc/work/core2-64-oe-linux/pipewire/0.3.67-r0/build=/usr/src/debug/pipewire/0.3.67-r0 -fdebug-prefix-map=TOPDIR/tmp-glibc/work/core2-64-oe-linux/pipewire/0.3.67-r0/recipe-sysroot= -fmacro-prefix-map=TOPDIR/tmp-glibc/work/core2-64-oe-linux/pipewire/0.3.67-r0/recipe-sysroot= -fdebug-prefix-map=TOPDIR/tmp-glibc/work/core2-64-oe-linux/pipewire/0.3.67-r0/recipe-sysroot-native= -fvisibility-inlines-hidden -fPIC -DWEBRTC_LIBRARY_IMPL -DWEBRTC_POSIX -DNOMINMAX -MD -MQ spa/plugins/aec/libspa-aec-webrtc.so.p/aec-webrtc.cpp.o -MF spa/plugins/aec/libspa-aec-webrtc.so.p/aec-webrtc.cpp.o.d -o spa/plugins/aec/libspa-aec-webrtc.so.p/aec-webrtc.cpp.o -c ../git/spa/plugins/aec/aec-webrtc.cpp
../git/spa/plugins/aec/aec-webrtc.cpp: In function 'int webrtc_init(void*, const spa_dict*, const spa_audio_info_raw*)':
../git/spa/plugins/aec/aec-webrtc.cpp:64:28: error: 'ExtendedFilter' is not a member of 'webrtc'
   64 |         config.Set<webrtc::ExtendedFilter>(new webrtc::ExtendedFilter(extended_filter));
      |                            ^~~~~~~~~~~~~~
../git/spa/plugins/aec/aec-webrtc.cpp:64:48: error: expected type-specifier
   64 |         config.Set<webrtc::ExtendedFilter>(new webrtc::ExtendedFilter(extended_filter));
      |                                                ^~~~~~
../git/spa/plugins/aec/aec-webrtc.cpp:65:28: error: 'DelayAgnostic' is not a member of 'webrtc'
   65 |         config.Set<webrtc::DelayAgnostic>(new webrtc::DelayAgnostic(delay_agnostic));
      |                            ^~~~~~~~~~~~~
../git/spa/plugins/aec/aec-webrtc.cpp:65:47: error: expected type-specifier
   65 |         config.Set<webrtc::DelayAgnostic>(new webrtc::DelayAgnostic(delay_agnostic));
      |                                               ^~~~~~
../git/spa/plugins/aec/aec-webrtc.cpp:76:86: error: 'Create' is not a member of 'webrtc::AudioProcessing'
   76 |         auto apm = std::unique_ptr<webrtc::AudioProcessing>(webrtc::AudioProcessing::Create(config));
      |                                                                                      ^~~~~~
../git/spa/plugins/aec/aec-webrtc.cpp:88:65: error: 'webrtc::EchoCancellation' has not been declared
   88 |         apm->echo_cancellation()->set_suppression_level(webrtc::EchoCancellation::kHighSuppression);
      |                                                                 ^~~~~~~~~~~~~~~~
../git/spa/plugins/aec/aec-webrtc.cpp:89:53: error: 'webrtc::NoiseSuppression' has not been declared
   89 |         apm->noise_suppression()->set_level(webrtc::NoiseSuppression::kHigh);
      |                                                     ^~~~~~~~~~~~~~~~
../git/spa/plugins/aec/aec-webrtc.cpp:94:47: error: 'webrtc::GainControl' has not been declared
   94 |         apm->gain_control()->set_mode(webrtc::GainControl::kAdaptiveDigital);
      |                                               ^~~~~~~~~~~
../git/spa/plugins/aec/aec-webrtc.cpp:45:14: warning: unused variable 'extended_filter' [-Wunused-variable]
   45 |         bool extended_filter = webrtc_get_spa_bool(args, "webrtc.extended_filter", true);
      |              ^~~~~~~~~~~~~~~
../git/spa/plugins/aec/aec-webrtc.cpp:46:14: warning: unused variable 'delay_agnostic' [-Wunused-variable]
   46 |         bool delay_agnostic = webrtc_get_spa_bool(args, "webrtc.delay_agnostic", true);
      |              ^~~~~~~~~~~~~~

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>