sanlock: Replace cp -a with cp -R --no-dereference
helps to stop leaking builder's UID into sstate cache

Fixes
Exception: KeyError: 'getpwuid(): uid not found: 6000'

Signed-off-by: Khem Raj <raj.khem@gmail.com>
(cherry picked from commit 80d4d7538a85123603eea3d87542c1c0433febb7)
[ak: fixes build issue
Exception: KeyError: 'getpwuid(): uid not found: 1000']
Signed-off-by: Armin Kuster <akuster808@gmail.com>
(cherry picked from commit 9e60d30669a2ad0598e9abf0cd15ee06b523986b)
[AK: fix for warrior context]
Signed-off-by: Armin Kuster <akuster808@gmail.com>